services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: reservex
      POSTGRES_USER: reservex
      POSTGRES_PASSWORD: reservex
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
